### ISSUE TITLE
Resolving calls

### ISSUE THREAD

**Issue by lausdahl** [overturetool/vdm2c#1]
Cite from language manual:

> In general, all constructs defined within a class must have a unique name, e.g. it is not allowed to define an operation and a type with the same name. However, it is possible to overload function and operation names (i.e. it is possible to have two or more functions with the same name and two or more operations with the same name) subject to the restriction that the types of their input parameters should not overlap. That is, it should be possible using static type checking alone to determine uniquely and unambiguously which function/operation definition corresponds to each function/operation call. Note that this applies not only to functions and operations defined in the local interface of a class but also to those inherited from superclasses. Thus, for example, in a design involving multiple inheritance a class C may inherit a function from a class A and a function with the same name from a class B and all calls involving this function name must be resolvable in class C.

Then this must be ok:

```
class Call1 is subclass of Call2
operations

public test2 : int|char==>int
test2(a)== return op(a);

public op:int==>int
op(-)==return 1;

end Call1

class Call2
operations

public op:char==>int
op(-)==return 2;

end Call2
```

well not according to the Overture interpreter when started with `new Call1().test2(1)`: `Error 4087: Cannot convert 1 (nat1) to char in 'Call1'`

why take the super `op` over the local `op` in `Call1`?

then lets reorder:

```
class Call1
operations

public test2 : int|char==>int
test2(a)== return op(a);

public op:int==>int
op(-)==return 1;

public op:char==>int
op(-)==return 2;

end Call1
```

well then we get: `Name op((char | int)) is ambiguous. 1: in 'Call1'` as a type check error.

I would have assumed that we pick the `op` that is closest to the type it is called from with the first dynamically matched arguments. 
1. Check local `op` first to see if arg types match at runtime
2. Check first declared super, all they way down to the root
3. Check next super, ...

one of them should match because they type checker should check that one which potentially could match exist.

**Comment by nickbattle** [comment]
I think that the spec should be legal, as the operations are distinguishable by their parameter types. So it looks like there is a problem with binding (the first case) and overload checking (the second case). I'll have a look when I get a minute.

**Comment by nickbattle** [comment]
OK, I think I can see a little more about what is going on here, and it relates to my earlier email about OO differences between VDM++, Java and C++.

In the first "binding" problem, there is no ambiguity error because VDMJ/Overture is behaving like C++ rather than Java, regarding overrides and overloads. Essentially, if you override something in C++, then inherited members that would otherwise overload "with" the override are hidden. I'm not sure what happens in Java here, to be honest. There is a nice StackOverflow description of the issue here: http://stackoverflow.com/questions/1628768/why-does-an-overridden-function-in-the-derived-class-hide-other-overloads-of-the. As often happens, C++ does things for a very good reason, and I think we should not naively follow Java semantics unless there is a good reason.

Unfortunately, although the type checking is like this for a reason, it looks like the runtime binding is not following the same rules! This is a bug therefore - VDMJ should be consistent, even if the rules are unclear. Do you know what VDMTools does in this case?

In the second case, you have a simple overload (no overriding) and VDMJ/Overture is quite right that the binding is ambiguous, because it cannot tell which operation should be called - note, I'm assuming that the binding is static, and it doesn't choose the op at runtime.

**Comment by nickbattle** [comment]
OK, I have a fix for the inconsistent binding problem (in VDMJ - I'll apply it to Overture soon). So with the first version of the spec, you now get:

```
> p new Call1().test2(1)
= 1
Executed in 0.017 secs. 
> p new Call1().test2('a')
Error 4087: Cannot convert 'a' (char) to int in 'Call1' (test.vpp) at line 11:23
Stopped in 'Call1' (test.vpp) at line 11:23
11:     test2(a)== return op(a);
```

So the "char" version has not been inherited, since it would overload the local definition. This is now reflected in the runtime context, as well as the type checking environment.

**Comment by lausdahl** [comment]
Thanks for the feedback so far. I think this simplifies my translation a bit in some cases (actually the naive selection I made so far actually seems to implement the right semantics here).

I recall the workshop in London (http://overturetool.org/workshops/8th-Overture-Workshop.html, just reformatted the workshop page it had some issue with the images/links)

**Comment by nickbattle** [comment]
Another good one in C++ is that it "isolates" class hierarchy construction. So if a hierarchy has an operation called "op" and, for some admittedly bizarrre reason, you want to call op during the construction of one of the parent classes (perhaps as a field initializer), C++ will use the version of "op" that the class would see if it was being constructed by itself (ie. not as someone else's parent). Java, on the other hand, calls the version of "op" that the ultimate child class would see - except that this class hasn't had its parents fully constructed yet! Here again, the C++ rules are much more sensible, and allow VDM++ to retain some control over its behavioiur and analysis.

**Comment by nickbattle** [comment]
This is now fixed in the Overture repo (ncb/development). I created an issue there, since this is really a problem with VDMJ/Overture, not your C translation as such.

**Comment by peterwvj** [comment]
As you said, this is an Overture/VDMJ issue so I'll close it.
