### ISSUE TITLE
usage of the IO library

### ISSUE THREAD

**Issue by nlmave** [overturetool/vdm2c#23]
Running the c-code generator after including the IO standard library fails:

An internal error occurred during: "VDM to C code generation".
org/overture/ast/types/ASetType

(vdm2c version 0.0.2 on Overture 2.4.0 both Windows 64-bit and Linux 32 bit)

**Comment by peterwvj** [comment]
I don't think this is related to the IO lib as such. At least, I'm not able to produce this problem. I also tried to code-generate a model that uses set types, but still I did not manage to produce a similar error. Could you attach or email me the model that produces this problem.

**Comment by peterwvj** [comment]
I take that back :) I was finally able to produce it using 0.0.2. I'll look into it.

**Comment by peterwvj** [comment]
Okay, I know what's up. VDM2C, version 0.0.2,  is built as a plugin that depends on Overture 2.3.6 - a version of Overture that does not support the `set1` type constructor. However, Overture 2.4.0, which adds the `set1` type constructor, has changed the structure of the tree to not include `ASetType`. Usually all core components (e.g. the AST) are exported by a plugin to make these components available to other plugins. Since version 2.4.0 of the AST does not include `ASetType`, OSGI fails to load this class when  VDM2C needs it (recall that OSGI uses dynamic loading).

Since I updated VDM2C to use the newest version of Overture, which does not use `ASetType`, the specific problem being reported is fixed in future releases. That's the good news. The workaround for now is to use Overture 2.3.8. However, there is a more fundamental issue which makes VDM2C vulnerable to AST changes. This is mostly an architectural problem, but I'll talk with Kenneth tomorrow in order to find a good way to approach this problem.

**Comment by peterwvj** [comment]
Fix confirmed to work - e64c4d6e12b73b6a5ecd645eb105f79bd08cde0f
