### ISSUE TITLE
Copy native lib from both CLI and IDE

### ISSUE THREAD

**Issue by bandurvp** [overturetool/vdm2c#31]
Move code that is responsible for copying the native lib so that this can be done by both the CLI and the IDE.  Check:

 https://github.com/overturetool/overture-fmu/blob/development/core/fmu-import-export/src/main/java/org/overturetool/fmi/export/CGenerator.java

https://github.com/overturetool/overture-fmu/blob/development/core/fmu-import-export/pom.xml

**Comment by peterwvj** [comment]
Hi @bandurvp. I assume you mean that you want to move the code that outputs the native library to the core so that it can be used by both the CLI and the IDE? So as far as I understand this method must extract the native library sources from `vdmclibJar` to `outputfolder`. Does this sound reasonable? The signature of this method would then be:

```Java
public static void copyNativeLibFiles(InputStream vdmclibJar, File outfolder) { ... }
```

**Comment by bandurvp** [comment]
Hi @peterwvj , yes this sounds right.
