### ISSUE TITLE
Complete support for records

### ISSUE THREAD

**Issue by peterwvj** [overturetool/vdm2c#33]
Initial work on records is available on the development branch, I just need to port it over and finish it.

**Comment by peterwvj** [comment]
I managed to make some progress on translation of records. Unfortunately I forgot to reference this issue in the commits. Anyway, below is a summary :) First, I should say that all my work related to translation of records is available on the `pvj/records` branch. I won't merge it into `pvj/main` yet.

I updated the code generator to convert record declarations and types to their class equivalents, which works well. However, since classes and records use reference and value semantics, respectively, we need to make sure that record values are deep cloned when they are passed around. I'm not sure how the C code generator deals with this, and if this can be handled entirely by the runtime. Anyway, this is just to say that I need your input on this @bandurvp :) It would simplify the translation if the `vdmClone` function could determine whether a value needs to be cloned or not. I'm not sure if that's possible? Perhaps we can discuss this tomorrow on Skype if you're not coming in?

**Comment by bandurvp** [comment]
As it stands, the distinction can definitely be made in the native lib, but we'll have to take a look at the whole picture.  It might be as simple as setting the VDM type in the generated value to VDM_RECORD instead of VDM_CLASS.  Let's look at it tomorrow.

**Comment by peterwvj** [comment]
Sounds promising :) I was hoping for something like that. Yeah, let's look at it tomorrow.

**Comment by bandurvp** [comment]
It looks like assignments of class instances to variables do not use vdmClone at the present.  Classes don't strictly need this, but records do.  As we discussed earlier today, it would be nice and uniform if they all used vdmClone, and the distinction can be made in the native lib.

**Comment by peterwvj** [comment]
Yeah it seems like the current approach is not quite right. What I think we need to do is to clone record values every time they appear as variable expressions or are returned as results of collection lookups. The Java code generator takes a similar approach. If you `grep` for `Utils.copy` in `overture/core/codegen/javagen`, which is equivalent to `vdmClone`, you'll see that this is exactly what it does.

```
/AFieldExpIR.vm:4:  Utils.copy(${field})##
/AFieldNumberExpIR.vm:14:       Utils.copy(${field})##
/AApplyExpIR.vm:19:     Utils.copy(${seqRead})
/AApplyExpIR.vm:33:     Utils.copy(${mapRead})
/AHeadUnaryExpIR.vm:10:     Utils.copy(${call})
/AExplicitVarExpIR.vm:2:Utils.copy($JavaFormat.format($node.getClassType()).$node.getName())##
/AIdentifierVarExpIR.vm:2:Utils.copy(${node.getName()})#
```

**Comment by peterwvj** [comment]
To clarify:

| Node type | VDM example |
| --- | :-: |
| AFieldExpIR | `obj.field` |
| AFieldNumberExpIR | `tuple.#5` |
| AApplyExpIR (first) | `mySeq(1)` |
| AApplyExpIR (second) | `myMap(5)` |
| AHeadUnaryExpIR | `hd mySeq` |
| AExplicitVarExpIR | `MyClass` ``instanceVar` |
| AIdentifierVarExpIR | `var` |

So maybe I could try to update the templates to do this tomorrow. Any thoughts?

**Comment by bandurvp** [comment]
Yes I think that's the right approach.

**Comment by bandurvp** [comment]
Peter, in order to implement that method of walking along the fields of a class that we discussed yesterday, it turns out that I need access to the total number of fields in the struct.  Otherwise I can not figure out the total size of the struct.

My idea is to have a field, say "int numFields" in the corresponding class struct that gets initialized in the top-level constructor (the one with the mangled name) to the total number of fields.  The field "numFields" can be added to the struct in the template "AClassStateDeclIR.vm" and the initialization of the field can be done in the constructor just before the return statement.  Would you be able to add this?  Then I can continue working out the clone, equality and free functions on the assumption that this field exists.  What do you think?

**Comment by peterwvj** [comment]
To remind myself I need update the mangled constructors to emit

``` C
SET_FIELD_PTR(<classname>, <classname>, this, numFields, newInt(<val>));
```

**Comment by bandurvp** [comment]
Hi Peter, I've been developing this value semantics scheme further and it seems that my idea of just adding "numFields" to the template is not enough, because there has to be a corresponding initialization of that field to NULL in one of the constructors.  The problem is that this initialization gets generated when that constructor itself gets generated, meaning that the field has to be in place already.  I think the natural thing to do is to add that field to each of the VDM classes before any code generation actions take place, so that it is there just like all the fields when this process starts.  I think this means adding it to the VDM AST or maybe to the IR, but I'm not sure about that second one.  Can you think of a better phase at which to do this?

**Comment by bandurvp** [comment]
Hi Peter, moreover I just realized that the field "numFields" _must_ be the first field of the class.  The reason is that the generated name of the field will contain the class structure's name, so it can not be accessed generically from the runtime.  But if it is the first field of the class, then I know its location and I can access it using pointer arithmetic.

**Comment by peterwvj** [comment]
That's fine with me. I can add an IR transformations that adds the `numField`, as the first field, to each class.
