### ISSUE TITLE
The plugin includes test classes in the vdmlib copied to the generated/c folder

### ISSUE THREAD

**Issue by lausdahl** [overturetool/vdm2c#4]

**Comment by peterwvj** [comment]
I had a quick look at this. The VDM2C code generator copies the content of `<vdm2c-root>/c/vdmclib/src` into the `generated` folder (or some subfolder). The problem is that `<vdm2c-root>/c/vdmclib/src` contains test/playground code, which shouldn't be there. To address this issue the `<vdm2c-root>/c/vdmclib/src` folder needs to be cleaned up. @bandurvp you know the runtime better than I do. Would you mind having a look?

**Comment by lausdahl** [comment]
The current way would probably be to split this into: a library, and a test project. Remember to update all CMakeLists.txt accordingly and check that it doesn’t break the build server job (I dont think it will but better make sure the tests continue to run)

otherwise the sources can be filtered during copy so only certain files/folders are copied.

**Comment by peterwvj** [comment]
This is related to #16
