### ISSUE TITLE
vdm map update support in transformation

### ISSUE THREAD

**Issue by miranha** [overturetool/vdm2c#54]
Currently we cannot update a map, we get the library call from the Java code generator, e.g. vdmMapUpdate:

Example:
fcus : map  Controller to FcuInfo := {|->};
...	
	for all f in set fs do
		fcus(f) := mk_FcuInfo(0,0,0,0); -- NOTE: This is generted wrongly

**Comment by peterwvj** [comment]
I added tests to check that collection updates are handled correctly. Currently, sequence updates work, but map updates do not. The problem is that the generated code assumes the existence of a function `vdmMapUpdate`, which does not exist. I've informed Victor about this and he is now working on updating the runtime.
