### ISSUE TITLE
VdmSequence - ASN.1 Sequence

### ISSUE THREAD

**Issue by tfabbri** [overturetool/vdm2c#90]
During the development of the TASTE support, I'm noting a different behavior for test applications compiled through clang-(Apple LLVM 7.0.2) and gcc-4.9.2 (Linux). A simple code like the following arise a SEGFAULT in clang and works like a charm in the gcc.

```
TVP test_seq = newSeq(5);
UNWRAP_COLLECTION(col, test_seq);
```

**Comment by bandurvp** [comment]
Hi @tfabbri ,
The reason you're getting this with clang is that, in this specific case, the function ```newSeq()``` is not declared in the header file ```VdmSeq.h```, since it is meant as an internal function (I should have perhaps made it ```static```).  You should see a compiler warning for this.  What happens is that the compiler infers the wrong type for it and it all goes downhill from there.  With GCC this does not lead to a segfault, but it does not work well either.  Clang is better and segfaults.  Let me know if you get the same issue when you use one of the functions declared in ```VdmSeq.h```, say ```newSeqVar()```.

**Comment by tfabbri** [comment]
You are right. 
There is an implicit-declaration warning at the newSeq call. 
I've changed to newSeqVar, and not it seems work. Thank you so much Victor

**Comment by tfabbri** [comment]
Hi @bandurvp, 

just a quick update: as you said `newSeq` is an internal function. The function `newSeqVar` requires the TVPs to insert into the sequence. If I want an empty sequence with a specified sized, I have to use the `newCollection` function or there is an other specific library function?

**Comment by bandurvp** [comment]
Hi @tfabbri , ```newCollection``` is also an internal function, so you should not use it.  You can use ```newSeqVarToGrow(initial_size, expected_size, ...)```, pass it an initial size of 0 and the specified size.  The rest of the arguments can be omitted since the initial size is zero.  The purpose of this function is that it preallocates memory to ```expected_size```.

**Comment by tfabbri** [comment]
@bandurvp  so, if I am correct, following the approach developed to add new elements to the vdm sequence I have to call `vdmSeqGrow` for each new TVP to insert. And to read I have to call `vdmSeqIndex`? 
Lot of changes have been done in vdmclib :)

**Comment by bandurvp** [comment]
Hi @tfabbri , yes that's the way to add to sequences and to access you use ```vdmSeqIndex```.  Don't forget that VDM uses 1-based indexing!  I don't think this changed since the initial versions of VDM2C...
